name: Continuous Integration

on:
  pull_request:
    branches: [ develop, main ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Client and Server
        run: npm install --if-present
      - name: Build Client
        run: npm run build --if-present
        env:
          CI: false
