name: Client - Continuous Integration Check

on:
  pull_request:
    branches: [ main, develop ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - run: cd client && npm ci
      - run: cd client && npm test
      - run: cd client && npm run build